dict_FT_h = {"idGame": "idGame", "Date": "Date",
             "IdTeam": "Id_Team_Home",
             "nWeek": "nWeek", "year": "year",
             "nWeekHome": "nWeekHome",
             "Referee": "Referee",
             'FTG_asH': 'Goals_H',
             'FTG_asH_last_3_strength': 'Goals_H_SA_last_3',
             'FTG_asH_last_6_strength': 'Goals_H_SA_last_6',
             'FTG_asH_last_10_strength': 'Goals_H_SA_last_10',
             'FTG_asH_last_infinity_strength': 'Goals_H_SA_last_infinity',
             "FTG_asH_last_3_mean": 'Goals_H_SA_last_3_mean',
             "FTG_asH_last_6_mean": 'Goals_H_SA_last_6_mean',
             "FTG_asH_last_10_mean": 'Goals_H_SA_last_10_mean',
             "FTG_asH_last_infinity_mean": 'Goals_H_SA_last_infinity_mean',
             "FT_against_H_last_3_strength": 'Goals_H_SD_last_3',
             "FT_against_H_last_6_strength": 'Goals_H_SD_last_6',
             "FT_against_H_last_10_strength": 'Goals_H_SD_last_10',
             "FT_against_H_last_infinity_strength": 'Goals_H_SD_last_infinity',
             "FT_against_H_last_3_mean": 'Goals_H_SD_last_3_mean',
             "FT_against_H_last_6_mean": 'Goals_H_SD_last_6_mean',
             "FT_against_H_last_10_mean": 'Goals_H_SD_last_10_mean',
             "FT_against_H_last_infinity_mean": 'Goals_H_SD_last_infinity_mean'
             }

dict_FT_a = {"idGame": "idGame", "Date": "Date",
             "IdTeam": "Id_Team_Away",
             "nWeek": "nWeek", "year": "year",
             "nWeekAway": "nWeekAway",
             "Referee": "Referee",
             'FTG_asA': 'Goals_A',
             'FTG_asA_last_3_strength': 'Goals_A_SA_last_3',
             'FTG_asA_last_6_strength': 'Goals_A_SA_last_6',
             'FTG_asA_last_10_strength': 'Goals_A_SA_last_10',
             'FTG_asA_last_infinity_strength': 'Goals_A_SA_last_infinity',
             "FTG_asA_last_3_mean": 'Goals_A_SA_last_3_mean',
             "FTG_asA_last_6_mean": 'Goals_A_SA_last_6_mean',
             "FTG_asA_last_10_mean": 'Goals_A_SA_last_10_mean',
             "FTG_asA_last_infinity_mean": 'Goals_A_SA_last_infinity_mean',
             "FT_against_A_last_3_strength": 'Goals_A_SD_last_3',
             "FT_against_A_last_6_strength": 'Goals_A_SD_last_6',
             "FT_against_A_last_10_strength": 'Goals_A_SD_last_10',
             "FT_against_A_last_infinity_strength": 'Goals_A_SD_last_infinity',
             "FT_against_A_last_3_mean": 'Goals_A_SD_last_3_mean',
             "FT_against_A_last_6_mean": 'Goals_A_SD_last_6_mean',
             "FT_against_A_last_10_mean": 'Goals_A_SD_last_10_mean',
             "FT_against_A_last_infinity_mean": 'Goals_A_SD_last_infinity_mean'
             }
